export const chipList = [
  'Dogs on leash',
  'Kid Friendly',
  'Hiking',
  'Horseback riding',
  'Snowshoing',
  'Bird watching',
  'Running',
  'Forest',
  'Lake',
  'Partially paved',
  'River',
  'Views',
  'Waterfall',
  'Wildflowers',
  'Wildlife',
  'Rocky',
  'Hsitoric site',
  'Fee',
];
export const exploreData = [
  'Trailsh',
  'Kid Friendly',
  'Hiking',
  'Horseback riding',
  'Snowshoing',
  'Bird watching',
  'Running',
  'Forest',
  'Lake',
  'Partially paved',
  'River',
  'Views',
  'Waterfall',
  'Wildflowers',
  'Wildlife',
  'Rocky',
  'Hsitoric site',
  'Fee',
];
export const sortbyData = ['Newest First', 'Kid Friendly', 'Hiking'];
export const timeOut = 2000;
