version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    env_file:
      - .env
    volumes:
      - static_volume:/app/client/build
      - shm:/dev/shm

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8004:80
    depends_on:
      - app
    volumes:
      - static_volume:/app/client/build
      - shm:/dev/shm
    container_name: trailfrontend

volumes:
  static_volume:
  shm:
